//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoraCommonTest.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ACCOUNT0_EMAIL {
            get {
                return ((string)(this["ACCOUNT0_EMAIL"]));
            }
            set {
                this["ACCOUNT0_EMAIL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ACCOUNT0_PASSWORD {
            get {
                return ((string)(this["ACCOUNT0_PASSWORD"]));
            }
            set {
                this["ACCOUNT0_PASSWORD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ACCOUNT0_VERIFICATION_CODE {
            get {
                return ((string)(this["ACCOUNT0_VERIFICATION_CODE"]));
            }
            set {
                this["ACCOUNT0_VERIFICATION_CODE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ACCOUNT1_EMAIL {
            get {
                return ((string)(this["ACCOUNT1_EMAIL"]));
            }
            set {
                this["ACCOUNT1_EMAIL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ACCOUNT1_PASSWORD {
            get {
                return ((string)(this["ACCOUNT1_PASSWORD"]));
            }
            set {
                this["ACCOUNT1_PASSWORD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ACCOUNT1_FIRST_SUBSCRIBER_IMSI {
            get {
                return ((string)(this["ACCOUNT1_FIRST_SUBSCRIBER_IMSI"]));
            }
            set {
                this["ACCOUNT1_FIRST_SUBSCRIBER_IMSI"] = value;
            }
        }
    }
}
